application:
  subdomain: file-drop
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://file-drop:3232/
services:
  file-drop:
    # upstream: ghcr.io/besoeasy/originless:20260917
    image: ghcr.1ms.run/besoeasy/originless:20260917
