lzc-sdk-version: "0.1"
name: File Drop
package: lazycat.community.app.file-drop
version: 1.0.3
description: A decentralized, open-source solution for sharing images, videos, and any other files.
homepage: https://github.com/besoeasy/file-drop
author: besoeasy
application:
  subdomain: file-drop
  background_task: true
  public_path:
    - /
  routes:
    - /=http://file-drop:3232

services:
  file-drop:
    # ghcr.io/besoeasy/file-drop:1.0.3
    image: registry.lazycat.cloud/czyt/besoeasy/file-drop:f9af9439b636864a
