package: lazycat.community.app.file-drop
version: 2026.8.27
name: File Drop
description: "A decentralized, open-source solution for sharing images, videos, and any other files."
min_os_version: "1.5.0"
homepage: https://github.com/besoeasy/file-drop
author: besoeasy
locales:
  zh:
    description: "一个去中心化的开源文件分享解决方案，支持分享图片、视频及其他任意文件。"
    name: File Drop
  en:
    description: "A decentralized, open-source solution for sharing images, videos, and any other files."
    name: File Drop
